export const ContractVideos = [
  {
    name:
      "لحظة توقيع عقد رواية قمر و الثوب الابيض للكاتب المصري ياسر عبدالحميد",
    url: "https://www.youtube.com/embed/G_P_x-0RZPA",
    id: "G_P_x-0RZPA",
    poster: "https://i.ytimg.com/vi/G_P_x-0RZPA/hqdefault.jpg",
    category: "main",
    itemIndex: 0,
    playing: "false",
  },
  {
    name: "لحظة توقيع عقد رواية الف حكاية و حكاية للكاتبة شيماء سعيد",
    url: "https://www.youtube.com/embed/izDA6oclvEA",
    id: "izDA6oclvEA",
    poster: "https://i.ytimg.com/vi/izDA6oclvEA/hqdefault.jpg",
    category: "main",
    itemIndex: 1,
    playing: "false",
  },
  {
    name: "لحظة توقيع عقد كتاب الخواطر( قنديل)",
    url: "https://www.youtube.com/embed/C8gzBc-PTRc",
    id: "C8gzBc-PTRc",
    poster: "https://i.ytimg.com/vi/C8gzBc-PTRc/hqdefault.jpg",
    category: "main",
    itemIndex: 2,
    playing: "false",
  },
  {
    name: "لحظة توقيع عقد رواية تلك الفاتنة للكاتبة نسمة مالك",
    url: "https://www.youtube.com/embed/2bB0O9Ojz9w",
    id: "2bB0O9Ojz9w",
    poster: "https://i.ytimg.com/vi/2bB0O9Ojz9w/hqdefault.jpg",
    category: "main",
    itemIndex: 3,
    playing: "false",
  },
  {
    name: "لحظة توقيع عقد كتاب (معنيات) للكاتب السوري معن الحمودي",
    url: "https://www.youtube.com/embed/F1K-kTtvyDg",
    id: "F1K-kTtvyDg",
    poster: "https://i.ytimg.com/vi/F1K-kTtvyDg/hqdefault.jpg",
    category: "main",
    itemIndex: 4,
    playing: "false",
  },
  {
    name:
      "لحظة توقيع عقد رواية شيوخ لا تعرف الحب ، بريشة العراقية نازك الحمراني",
    url: "https://www.youtube.com/embed/PCwmBBY5cw0",
    id: "PCwmBBY5cw0",
    poster: "https://i.ytimg.com/vi/PCwmBBY5cw0/hqdefault.jpg",
    category: "main",
    itemIndex: 5,
    playing: "false",
  },
  {
    name: "لحظة توقيع عقد روايتين عراقية ×بحرينية",
    url: "https://www.youtube.com/embed/5qlyPcUX8G8",
    id: "5qlyPcUX8G8",
    poster: "https://i.ytimg.com/vi/5qlyPcUX8G8/hqdefault.jpg",
    category: "main",
    itemIndex: 6,
    playing: "false",
  },
  {
    name:
      "لحظة توقيع الكاتب المصري المتألق أ.وليد صلاح لعقد روايته الخادم الأخير",
    url: "https://www.youtube.com/embed/60upLAl8aVc",
    id: "60upLAl8aVc",
    poster: "https://i.ytimg.com/vi/60upLAl8aVc/hqdefault.jpg",
    category: "main",
    itemIndex: 7,
    playing: "false",
  },
  {
    name: "لحظة توقيع عقد رواية الخطيئة للروائي المصري تامر محمد عزت",
    url: "https://www.youtube.com/embed/yqKh7sAtOTA",
    id: "yqKh7sAtOTA",
    poster: "https://i.ytimg.com/vi/yqKh7sAtOTA/hqdefault.jpg",
    category: "main",
    itemIndex: 8,
    playing: "false",
  },
  {
    name: "لحظة توقيع عقد رواية الهجين [روح آدم] للروائية اليمنية رباب",
    url: "https://www.youtube.com/embed/0p__mm9jSF4",
    id: "0p__mm9jSF4",
    poster: "https://i.ytimg.com/vi/0p__mm9jSF4/hqdefault.jpg",
    category: "main",
    itemIndex: 9,
    playing: "false",
  },
];
export default ContractVideos;
