// export const AkonOrgInnovData = [
//   {
//     name: "2020 أكون في معرض القاهرة الدولي",
//     url: "https://www.youtube.com/embed/KFDVA78XJU4",
//     id: "KFDVA78XJU4",
//     poster: "https://i.ytimg.com/vi/KFDVA78XJU4/hqdefault.jpg",
//     category: "main",
//     itemIndex: 0,
//     playing: "false",
//   },
//   {
//     name: "من نحن ؟!",
//     url: "https://www.youtube.com/embed/G33MNYPeeNM",
//     id: "G33MNYPeeNM",
//     poster: "https://i.ytimg.com/vi/G33MNYPeeNM/hqdefault.jpg",
//     category: "main",
//     itemIndex: 1,
//     playing: "false",
//   },
//   {
//     name: "تهنئة أكونية بطعم العنقاء : كل عام وانتم نبضنا",
//     url: "https://www.youtube.com/embed/mXZglwS5D_M",
//     id: "mXZglwS5D_M",
//     poster: "https://i.ytimg.com/vi/mXZglwS5D_M/hqdefault.jpg",
//     category: "main",
//     itemIndex: 2,
//     playing: "false",
//   },
//   {
//     name:
//       "الكاتبة العراقية حنين يعكوب ، تتحدث فيها عن تجربتها مع أول مطبوع ورقي لها في 2020",
//     url: "https://www.youtube.com/embed/QHLX5B_2DHI",
//     id: "QHLX5B_2DHI",
//     poster: "https://i.ytimg.com/vi/QHLX5B_2DHI/hqdefault.jpg",
//     category: "main",
//     itemIndex: 3,
//     playing: "false",
//   },
//   {
//     name: "توقيع عقد أربع روايات عراقية",
//     url: "https://www.youtube.com/embed/BZ-nrUedVjg",
//     id: "BZ-nrUedVjg",
//     poster: "https://i.ytimg.com/vi/BZ-nrUedVjg/hqdefault.jpg",
//     category: "main",
//     itemIndex: 4,
//     playing: "false",
//   },
//   {
//     name: "برومو رواية : ضربة القاضية لللمتألقة نيهال عبدالواحد",
//     url: "https://www.youtube.com/embed/g5bnTtbPVps",
//     id: "g5bnTtbPVps",
//     poster: "https://i.ytimg.com/vi/g5bnTtbPVps/hqdefault.jpg",
//     category: "main",
//     itemIndex: 5,
//     playing: "false",
//   },
//   {
//     name:
//       "شكرا للروائي الأردني أيمن عتوم على دعمه لمؤسسة( أكون أو أكون ) للإبداع العربي",
//     url: "https://www.youtube.com/embed/AkycK0NucTo",
//     id: "AkycK0NucTo-EhM21Ho",
//     poster: "https://i.ytimg.com/vi/AkycK0NucTo/hqdefault.jpg",
//     category: "main",
//     itemIndex: 6,
//     playing: "false",
//   },
//   {
//     name: "تغطية صحافية لمعرض القاهرة ج1",
//     url: "https://www.youtube.com/embed/dhcFOS_6teg",
//     id: "dhcFOS_6teg",
//     poster: "https://i.ytimg.com/vi/dhcFOS_6teg/hqdefault.jpg",
//     category: "main",
//     itemIndex: 7,
//     playing: "false",
//   },
//   {
//     name: "تغطية صحافية لمعرض القاهرة ج2",
//     url: "https://www.youtube.com/embed/zt57ukDFcrw",
//     id: "zt57ukDFcrw",
//     poster: "https://i.ytimg.com/vi/zt57ukDFcrw/hqdefault.jpg",
//     category: "main",
//     itemIndex: 8,
//     playing: "false",
//   },
// ];
// export default AkonOrgInnovData;
