export const NovelPromoData = [
  {
    name: `"برومو اول كتاب ورقي بختم أكون"  مجموعة القصصية الواح القرميد`,
    url: "https://www.youtube.com/embed/TzR5-U0-ysE",
    id: "TzR5-U0-ysE",
    poster: "https://i.ytimg.com/vi/TzR5-U0-ysE/hqdefault.jpg",
    category: "main",
    itemIndex: 0,
    playing: "false",
  },
  {
    name: "برومو رواية من اوراق الشباطين",
    url: "https://www.youtube.com/embed/9954M0dDftU",
    id: "9954M0dDftU",
    poster: "https://i.ytimg.com/vi/9954M0dDftU/hqdefault.jpg",
    category: "main",
    itemIndex: 1,
    playing: "false",
  },
  {
    name: "برومو كتاب الكتروني محموعة خواطر تراتيل ثائرة",
    url: "https://www.youtube.com/embed/UfyIHbVLFkY",
    id: "UfyIHbVLFkY",
    poster: "https://i.ytimg.com/vi/UfyIHbVLFkY/hqdefault.jpg",
    category: "main",
    itemIndex: 2,
    playing: "false",
  },
  {
    name: `برمو مجموعة خواطر :وبيننا موعد " للكاتبة مديمان علي السيد"`,
    url: "https://www.youtube.com/embed/eUlDQJisUqs",
    id: "eUlDQJisUqs",
    poster: "https://i.ytimg.com/vi/eUlDQJisUqs/hqdefault.jpg",
    category: "main",
    itemIndex: 3,
    playing: "false",
  },
  {
    name: "برومو كتاب الكتروني محموعة خواطر تياهر القلم",
    url: "https://www.youtube.com/embed/kMQ6C4hZrg4",
    id: "kMQ6C4hZrg4",
    poster: "https://i.ytimg.com/vi/kMQ6C4hZrg4/hqdefault.jpg",
    category: "main",
    itemIndex: 4,
    playing: "false",
  },
  {
    name: "برومو رواية : ضربة القاضية لللمتألقة نيهال عبدالواحد",
    url: "https://www.youtube.com/embed/xFzrOR51ZSA",
    id: "xFzrOR51ZSA",
    poster: "https://i.ytimg.com/vi/xFzrOR51ZSA/hqdefault.jpg",
    category: "main",
    itemIndex: 5,
    playing: "false",
  },
  {
    name: "برومو رائع لكتاب : انا و الحياة للكاتبة المتألقة رشا شاهين",
    url: "https://www.youtube.com/embed/ZwS-EhM21Ho",
    id: "ZwS-EhM21Ho",
    poster: "https://i.ytimg.com/vi/ZwS-EhM21Ho/hqdefault.jpg",
    category: "main",
    itemIndex: 6,
    playing: "false",
  },
];
export default NovelPromoData;
